---
- name: Creation d'une VM Onion pour CyberOps
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Creation de la vm a partir du template
    vmware_guest:
        validate_certs: False
        name: testAWX
        template: templateOnion
        datacenter: test
        folder: /templates

...


