---
- name: Creation de l'environnement CyberOps
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Creation de la vm CyberOps a partir du template
    vmware_guest:
        validate_certs: False
        name: "{{ namecyberops }}"
        template: templateCyberOps
        datacenter: test
        folder: /templates	
  - name: Creation de la vm Onion partir du template
    vmware_guest:
        validate_certs: False
        name: "{{ nameonion }}" 
        template: templateOnion
        datacenter: test
        folder: /templates
  - name: Creation de la vm Metasploit partir du template
    vmware_guest:
        validate_certs: False
        name: "{{ namemetasploit }}"
        template: templateMetasploit
        datacenter: test
        folder: /templates
...
